config/routes.rb
# == Route Map (Updated 2014-02-09 04:17)
#
#      Prefix Verb   URI Pattern               Controller#Action
#        root GET    /                         static_pages#home
#        help GET    /help(.:format)           static_pages#help
#       about GET    /about(.:format)          static_pages#about
#       users GET    /users(.:format)          users#index
#             POST   /users(.:format)          users#create
#    new_user GET    /users/new(.:format)      users#new
#   edit_user GET    /users/:id/edit(.:format) users#edit
#        user GET    /users/:id(.:format)      users#show
#             PATCH  /users/:id(.:format)      users#update
#             PUT    /users/:id(.:format)      users#update
#             DELETE /users/:id(.:format)      users#destroy
#      signup GET    /signup(.:format)         users#new
#    sessions POST   /sessions(.:format)       sessions#create
# new_session GET    /sessions/new(.:format)   sessions#new
#     session DELETE /sessions/:id(.:format)   sessions#destroy
#      signin GET    /signin(.:format)         sessions#new
#     signout DELETE /signout(.:format)        sessions#destroy
#       posts POST   /posts(.:format)          posts#create
#        post DELETE /posts/:id(.:format)      posts#destroy
#

Monkfish::Application.routes.draw do
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'

  resources :users
  match '/signup', to: 'users#new', via: 'get'
  
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :posts, only: [:show, :create, :destroy]

  resources :cohortships do
    collection do
      get :req
      get :accept
      get :reject      
    end
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>" class="feed-item">
  <span class="content">
  	<%= link_to feed_item.title, post_path(feed_item), remote: true %>
  </span>
  <span class="timestamp">
    <small>Posted <%= time_ago_in_words(feed_item.created_at) %> ago by <%= link_to feed_item.user.name, feed_item.user %></small>
  </span>
  <small>
    <% if current_user?(feed_item.user) %>
      <%= link_to "delete", feed_item, method: :delete,
                                       data: { confirm: "Are you sure?" },
                                       title: feed_item.content %>
    <% end %>
  </small>
</li>

app/views/shared/_notification_item.html.erb
<!--<li id="<%= feed_item.id %>" class="feed-item"><span class="content">
  	<%= link_to feed_item.title, prepend_url(feed_item.content), :target => '_blank' %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago by <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "Are you sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>-->

<li>
	<span>It</span>
	<span>looks like it</span>
	<span>worked.</span>
</li>

app/views/shared/_notifications.html.erb
<% if @feed_items.any? %>
	<ol class="posts">
	<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_area :content, placeholder: "URL" %>
  	<%= f.text_area :title, placeholder: "Title" %>
    <%= f.text_area :leading_comment, placeholder: "Your thoughts?" %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<div class="username-container">
	<h1 class="username">
  	<%= link_to current_user.name, current_user %>
	</h1>
	<button class="btn post-btn btn-primary" data-toggle="modal" data-target="#myModal"><span class="glyphicon glyphicon-link"></span></button>
</div>
<div class="panel-button-container">
  <ul class="pager">
    <li><%= link_to "Feed",    root_path %></li>
    <li><%= link_to "Notifications", users_path %></li>
  </ul>
</div>


<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Post a link</h4>
      </div>
      <div class="modal-body">
        <%= form_for(@post) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class="field">
            <%= f.text_area :content, placeholder: "URL" %>
            <%= f.text_area :title, placeholder: "Title" %>
            <%= f.text_area :leading_comment, placeholder: "Your thoughts?" %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">
        Close</button>
        <%= f.submit "Post", class: "btn btn-primary btn-submit-post" %>
        <% end %>
      </div>
    </div>
  </div>
</div>